# Docker
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'Publish Artifact: drop'
    publishLocation: 'pipeline'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: |
      mongovolume.yml
      mongovolumeclaim.yml
      mongo-deployment.yml
      mongo-service.yml
      mongo-endpoint.yml
      spring-deployment.yml
      spring-service.yml
      spring-ingress.yml
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '**/Dockerfile'
        tags: |
          $(tag)